#use_frameworks!

target 'ZHSTL_Example' do
  pod 'ZHSTL', :path => '../'

#  target 'ZHSTL_Tests' do
#    inherit! :search_paths
#
#    pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
#  end
end
